# Generated by Django 2.2.4 on 2019-08-30 06:58

from django.db import migrations, models
import image_upload_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/', validators=[image_upload_app.validators.validate_file_extension, image_upload_app.validators.validate_image])),
                ('Description', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
